apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account
  labels:
    heketi: sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: heketi-sa-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: heketi-service-account
  namespace: heketi
