---
kind: Service
apiVersion: v1
metadata:
  name: heketi-api
  namespace: heketi
  labels:
    heketi: service
  annotations:
    description: Exposes Heketi Service
spec:
  selector:
    heketi: app
  ports:
  - name: heketi-api
    port: 8080
    targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: heketi
  namespace: heketi
  labels:
    heketi: app
  annotations:
    description: Defines how to deploy Heketi
spec:
  replicas: 1
  selector:
    matchLabels:
      heketi: app
  template:
    metadata:
      name: heketi
      labels:
        heketi: app
    spec:
      serviceAccountName: heketi-service-account
      containers:
      - image: heketi/heketi:latest
        imagePullPolicy: IfNotPresent
        name: heketi
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        - name: config
          mountPath: /etc/heketi
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
        glusterfs:
          endpoints: heketi-storage-endpoints
          path: heketidbstorage
      - name: config
        secret:
          secretName: heketi-config
      hostAliases:
      - ip: "10.15.0.11"
        hostnames:
        - "jh-k8s-master001"
      - ip: "10.15.0.12"
        hostnames:
        - "jh-k8s-master002"
      - ip: "10.15.0.13"
        hostnames:
        - "jh-k8s-master003"