apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://ENDPOINTS"
  clusterid: "CLUSTER_ID"
  restauthenabled: "true"
  restuser: "admin"
  secretNamespace: "heketi"
  secretName: "heketi-resturl"
  gidMin: "40000"
  gidMax: "50000"
  volumetype: "replicate:3"